### ISSUE TITLE
Add a `color_scheme` member to `ImageResource`

### ISSUE THREAD

**Issue by aarongustafson** [w3c/manifest#758]
With operating systems beginning to offer multiple color schemes (e.g., “dark mode” and “light mode”) and with CSS offering a media query for that user preference, it is important to enable web apps to offer appropriate iconography for the context. As such, we need to upgrade the ImageResource dictionary to include an optional member indicating which color scheme a given image should be associated with.

I’ve worked up an explainer on this here: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/ImageResource-color_scheme/explainer.md

Related: #618

**Comment by marcoscaceres** [comment]
Generally, this sounds good. Would probably need to tweak to color_scheme values a little bit, but nothing big. Ideally, we would just reuse whatever CSS is using. Could you please provide a link?

**Comment by tomayac** [comment]
The spec for this is [here](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme). In CSS, you'd do something like this (greatly simplified):

```css
/* Default assumes light theme */
body {
  background-color: white;
  color: black;
}

/* For dark mode folk, invert */
@media (prefers-color-scheme: dark) {
  body {
    background-color: black;
    color: white;
  }
}
```

So we could either make the values of `theme_color` and `background_color` more complex by somehow adding alternatives; one idea could be `"theme_color": "black / @media (prefers-color-scheme: dark) white"` (similar to https://drafts.csswg.org/css-content/#alt).

Alternatively, we could add more properties like `theme_color_dark` and `background_color_dark`, which would be backwards compatible and simpler. And while [Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5/#mf-user-preferences) defines more user preference media queries, none of the other ones seem super relevant for Web App Manifest (apart from maybe `inverted-colors`), so we'd probably not have to introduce further properties for them.
